// <auto-generated />
using System;
using FinTrader.Pro.DB.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FinTrader.Pro.DB.Migrations
{
    [DbContext(typeof(FinTraderDataContext))]
    [Migration("20211008174726_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FinTrader.Pro.DB.Models.Bond", b =>
                {
                    b.Property<string>("SecId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<double?>("AccruedInt")
                        .HasColumnType("double");

                    b.Property<string>("BoardId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Comment")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<double?>("CouponPercent")
                        .HasColumnType("double");

                    b.Property<int?>("CouponPeriod")
                        .HasColumnType("int");

                    b.Property<double?>("CouponValue")
                        .HasColumnType("double");

                    b.Property<string>("CurrencyId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("Decimals")
                        .HasColumnType("int");

                    b.Property<bool>("Discarded")
                        .HasColumnType("tinyint(1)");

                    b.Property<double?>("Duration")
                        .HasColumnType("double");

                    b.Property<int?>("EmitterId")
                        .HasColumnType("int");

                    b.Property<string>("FaceUnit")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<double?>("FaceValue")
                        .HasColumnType("double");

                    b.Property<string>("Isin")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<long?>("IssueSize")
                        .HasColumnType("bigint");

                    b.Property<int?>("LotSize")
                        .HasColumnType("int");

                    b.Property<double?>("LotValue")
                        .HasColumnType("double");

                    b.Property<DateTime?>("MatDate")
                        .HasColumnType("datetime(6)");

                    b.Property<double?>("ModifiedDuration")
                        .HasColumnType("double");

                    b.Property<DateTime?>("NextCoupon")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("OfferDate")
                        .HasColumnType("datetime(6)");

                    b.Property<double?>("PrevWaPrice")
                        .HasColumnType("double");

                    b.Property<string>("SecName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("SecType")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ShortName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Status")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime(6)");

                    b.Property<double?>("ValueAvg")
                        .HasColumnType("double");

                    b.Property<double?>("Yield")
                        .HasColumnType("double");

                    b.Property<double?>("YieldAtPrevWaPrice")
                        .HasColumnType("double");

                    b.HasKey("SecId");

                    b.HasIndex("Isin");

                    b.ToTable("Bonds");
                });

            modelBuilder.Entity("FinTrader.Pro.DB.Models.Config", b =>
                {
                    b.Property<int>("BondsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(6);

                    b.Property<int>("MaxYield")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(15);

                    b.ToTable("Config");
                });

            modelBuilder.Entity("FinTrader.Pro.DB.Models.Coupon", b =>
                {
                    b.Property<int>("CouponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CouponDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FaceUnit")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<double?>("FaceValue")
                        .HasColumnType("double");

                    b.Property<double?>("InitialFaceValue")
                        .HasColumnType("double");

                    b.Property<string>("Isin")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<DateTime?>("RecordDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<double?>("Value")
                        .HasColumnType("double");

                    b.Property<double?>("ValuePrc")
                        .HasColumnType("double");

                    b.Property<double?>("ValueRub")
                        .HasColumnType("double");

                    b.HasKey("CouponId");

                    b.HasIndex("Isin");

                    b.ToTable("Coupons");
                });

            modelBuilder.Entity("FinTrader.Pro.DB.Models.TradeDate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("TradeDates");
                });
#pragma warning restore 612, 618
        }
    }
}
