-- public."TradeDates" definition

-- Drop table

-- DROP TABLE public."TradeDates";

CREATE TABLE public."TradeDates" (
	"Id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"Date" timestamp NOT NULL,
	CONSTRAINT "PK_TradeDates" PRIMARY KEY ("Id")
);

-- public."Coupons" definition

-- Drop table

-- DROP TABLE public."Coupons";

CREATE TABLE public."Coupons" (
	"CouponId" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"Isin" text NULL,
	"CouponDate" timestamp NULL,
	"RecordDate" timestamp NULL,
	"StartDate" timestamp NULL,
	"InitialFaceValue" float8 NULL,
	"FaceValue" float8 NULL,
	"FaceUnit" text NULL,
	"Value" float8 NULL,
	"ValuePrc" float8 NULL,
	"ValueRub" float8 NULL,
	CONSTRAINT "PK_Coupons" PRIMARY KEY ("CouponId")
);
CREATE INDEX "IX_Coupons_Isin" ON public."Coupons" USING btree ("Isin");

-- public."Config" definition

-- Drop table

-- DROP TABLE public."Config";

CREATE TABLE public."Config" (
	"BondsCount" int4 NOT NULL DEFAULT 6,
	"MaxYield" int4 NOT NULL DEFAULT 15
);

-- public."Bonds" definition

-- Drop table

-- DROP TABLE public."Bonds";

CREATE TABLE public."Bonds" (
	"SecId" text NOT NULL,
	"BoardId" text NULL,
	"Discarded" bool NOT NULL,
	"ShortName" text NULL,
	"PrevWaPrice" float8 NULL,
	"YieldAtPrevWaPrice" float8 NULL,
	"CouponValue" float8 NULL,
	"AccruedInt" float8 NULL,
	"LotSize" int4 NULL,
	"FaceValue" float8 NULL,
	"Status" text NULL,
	"MatDate" timestamp NULL,
	"Decimals" int4 NULL,
	"CouponPeriod" int4 NULL,
	"IssueSize" int8 NULL,
	"PrevDate" timestamp NULL,
	"SecName" text NULL,
	"FaceUnit" text NULL,
	"BuyBackPrice" float8 NULL,
	"BuyBackDate" timestamp NULL,
	"Isin" text NULL,
	"CurrencyId" text NULL,
	"SecType" text NULL,
	"CouponPercent" float8 NULL,
	"OfferDate" timestamp NULL,
	"LotValue" float8 NULL,
	"EmitterId" int4 NULL,
	"Duration" float8 NULL,
	"ModifiedDuration" float8 NULL,
	"Yield" float8 NULL,
	"ValueAvg" float8 NULL,
	"Comment" text NULL,
	"Updated" timestamp NOT NULL,
	"NextCoupon" timestamp NULL,
	CONSTRAINT "PK_Bonds" PRIMARY KEY ("SecId")
);
CREATE INDEX "IX_Bonds_Isin" ON public."Bonds" USING btree ("Isin");




SELECT b."SecId", b."AccruedInt", b."BoardId", b."BuyBackDate", b."BuyBackPrice", b."Comment", b."CouponPercent", b."CouponPeriod", b."CouponValue", b."CurrencyId", b."Decimals", b."Discarded", b."Duration", b."EmitterId", b."FaceUnit", b."FaceValue", b."Isin", b."IssueSize", b."LotSize", b."LotValue", b."MatDate", b."ModifiedDuration", b."NextCoupon", b."OfferDate", b."PrevDate", b."PrevWaPrice", b."SecName", b."SecType", b."ShortName", b."Status", b."Updated", b."ValueAvg", b."Yield", b."YieldAtPrevWaPrice"
      FROM "Bonds" AS b
      WHERE b."SecId" = @__get_Item_0
      LIMIT 1



